sudo: required

language: node_js

node_js:
  - "6"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
 — export DISPLAY=:99.0
 — sh -e /etc/init.d/xvfb start

before_script:
 - npm install -g angular-cli

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master